# Generated by Django 5.0.4 on 2024-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_author_alter_book_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
